### ISSUE TITLE
TrueNAS SCALE

### ISSUE THREAD

**Issue by horse-pants** [BitR/empyrion-docker#10]
Hi,
This isn't an issue but I didn't know how else to contact you (sorry). 
Firstly thanks for this project, super helpful
Second, I've had this running on TrueNAS SCALE for the last month or two and we haven't noticed any issues, I can send the various (I'd argue weird sometimes) settings TrueNAS requires if you think it'd be useful for the readme

Thanks

**Comment by BitR** [comment]
Glad you like it.
If you update this issue with your tweaks, I'll refer to it in README, which will allow you to update your recommendations as you see fit. I'm sure someone is running it in the same environment and will benefit from your findings.
Cheers
