### ISSUE TITLE
Server wont show online

### ISSUE THREAD

**Issue by daigonstar** [BitR/empyrion-docker#11]
Hi there I seem to be having a little trouble getting the server to show online. 
I converted to a compose as I'm using portainer and find stacks easier to manage.
and everything pulls correctly volumes are mapped properly the logs even say everything is fine.
I have forwarded ports 30000-30004 but steam still cant see it.

Here is the compose I used:

version: '2'
services:
  Empyrion:
    image: bitr/empyrion-server 
    container_name: empyrion
    volumes:
    - /home/empyrion/Empyrion:/home/user/Steam
      ports:
    - 30000:30000
    - 30001:30001
    - 30002:30002
    - 30003:30003
      restart: unless-stopped

I have also grabbed some logs from the server.

GfxDevice: creating device client; threaded=0
,
Direct3D:
,
    Version:  Direct3D 11.0 [level 10.1]
,
    Renderer: NVIDIA GeForce 8800 GTX (ID=0x191)
,
    Vendor:   
,
    VRAM:     31982 MB
,
Begin MonoManager ReloadAssembly
,
- Completed reload, in  0.173 seconds
,
D3D11 device created for Microsoft Media Foundation video decoding.
,
UnloadTime: 0.403000 ms
,
18-20:25:45.629 20_25 -LOG- Args: Z:\home\user\Steam\steamapps\common\Empyrion - Dedicated Server\DedicatedServer\EmpyrionDedicated.exe -batchmode -logFile Logs/current.log
,
18-20:25:45.645 20_25 -LOG- Dedi log path = Z:\home\user\Steam\steamapps\common\Empyrion - Dedicated Server\DedicatedServer\EmpyrionDedicated_Data\..\Logs
,
18-20:25:45.690 20_25 -LOG- *************************************************************************
,
18-20:25:45.690 20_25 -LOG- Dedicated Server Empyrion - Galactic Survival
,
18-20:25:45.690 20_25 -LOG- Version: v1.4.7
,
18-20:25:45.690 20_25 -LOG- Build: 3283
,
18-20:25:45.690 20_25 -LOG- Platform: Win, 64 Bit
,
18-20:25:45.690 20_25 -LOG- OS: Windows 7  (6.1.0) 64bit
,
18-20:25:45.690 20_25 -LOG- DRAM: 40174
,
18-20:25:45.690 20_25 -LOG- CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
,
18-20:25:45.690 20_25 -LOG- Freq: 4500
,
18-20:25:45.690 20_25 -LOG- Cores: 8
,
18-20:25:45.691 20_25 -LOG- Gfx: NVIDIA GeForce 8800 GTX
,
18-20:25:45.691 20_25 -LOG- VRAM: 31982
,
18-20:25:45.692 20_25 -LOG- SL: 4.5
,
18-20:25:45.692 20_25 -LOG- Force DX9: False
,
18-20:25:45.692 20_25 -LOG- Instancing: False
,
18-20:25:45.693 20_25 -LOG- TimeZone: +00:00
,
18-20:25:45.693 20_25 -LOG- Culture: en-US
,
18-20:25:45.693 20_25 -LOG- Last build: 0
,
18-20:25:45.693 20_25 -LOG- Dedicated server build
,
18-20:25:45.696 20_25 -LOG- Build: Release (nodePosition)
,
18-20:25:45.696 20_25 -LOG- MainThreadId: 50
,
18-20:25:45.696 20_25 -LOG- *************************************************************************
,
18-20:25:45.696 20_25 -LOG- Limiting the number of worker threads on a dedicated server to 7
,
18-20:25:45.928 20_25 -LOG- Loading file 'Z:\home\user\Steam\steamapps\common\Empyrion - Dedicated Server\DedicatedServer/../dedicated.yaml'
,
18-20:25:45.999 20_25 -LOG- Thread 'StampDB' ThreadId=83 ManagedId=4
,
18-20:25:46.007 20_25 -LOG- Save game version v1.4.7, Build 3283
,
18-20:25:46.218 20_25 -LOG- Loading override Config.ecf file 'Z:\home\user\Steam\steamapps\common\Empyrion - Dedicated Server\DedicatedServer/../Content/Scenarios/Reforged Eden\Content\Configuration\Config.ecf'
,
18-20:25:46.415 20_25 -LOG- Altering table StructuresHistory not successfull: SQL logic error
,
duplicate column name: pfid. Table already in correct format.
,
18-20:25:46.416 20_25 -LOG- Altering table TerrainPlaceables not successfull: SQL logic error
,
duplicate column name: tpentityid. Table already in correct format.
,
18-20:25:46.419 20_25 -LOG- Altering table LoginLogoff not successfull: SQL logic error
,
duplicate column name: fsize. Table already in correct format.
,
18-20:25:46.419 20_25 -LOG- Altering table DialogueVars not successfull: SQL logic error
,
duplicate column name: valuestr. Table already in correct format.
,
18-20:25:46.420 20_25 -LOG- Altering table PerformanceData not successfull: SQL logic error
,
duplicate column name: hitasks. Table already in correct format.
,
18-20:25:46.420 20_25 -LOG- Altering table PerformanceData not successfull: SQL logic error
,
duplicate column name: lotasks. Table already in correct format.
,
18-20:25:46.420 20_25 -LOG- Altering table PerformanceData not successfull: SQL logic error
,
duplicate column name: dbtasks. Table already in correct format.
,
18-20:25:46.420 20_25 -LOG- Altering table PerformanceData not successfull: SQL logic error
,
duplicate column name: queue0. Table already in correct format.
,
18-20:25:46.421 20_25 -LOG- Altering table PerformanceData not successfull: SQL logic error
,
duplicate column name: queue1. Table already in correct format.
,
18-20:25:46.421 20_25 -LOG- Altering table PerformanceData not successfull: SQL logic error
,
duplicate column name: queue2. Table already in correct format.
,
18-20:25:46.421 20_25 -LOG- Altering table PerformanceData not successfull: SQL logic error
,
duplicate column name: queue3. Table already in correct format.
,
18-20:25:46.421 20_25 -LOG- Altering table PerformanceNWPackages not successfull: SQL logic error
,
duplicate column name: type. Table already in correct format.
,
18-20:25:46.422 20_25 -LOG- Altering table Marketplace not successfull: SQL logic error
,
duplicate column name: maxtranscost. Table already in correct format.
,
18-20:25:46.437 20_25 -LOG- Game dat file loaded
,
18-20:25:48.226 20_25 -LOG- Loaded sector file Z:\home\user\Steam\steamapps\common\Empyrion - Dedicated Server\DedicatedServer/../Saves/Games/DaigonStar/Sectors/Sectors.yaml with 654 playfields, needed 1678ms
,
18-20:25:48.565 20_25 -LOG- Generating stars=45822 took 337
,
18-20:25:48.565 20_25 -LOG- Faction statistics enabled
,
18-20:25:48.565 20_25 -LOG- Mode=pathCount, GameSeed=1011345, UniqueId=827346774, EntityId=4001
,
18-20:25:48.570 20_25 -LOG- Task Type=childSession ThreadId=85 ManagedId=6
,
18-20:25:48.622 20_25 -LOG- Start Game
,
18-20:25:48.622 20_25 -LOG- Server started listening on port 30000
,
18-20:25:48.726 20_25 -LOG- EAC: Starting server
,
18-20:25:48.754 20_25 -LOG- Thread 'PublishResource1' ThreadId=108 ManagedId=8
,
18-20:25:48.754 20_25 -LOG- Now listening for PfServers on port 30003
,
Setting up 4 worker threads for Enlighten.
,
  Thread -> id: 72 -> priority: 1 
,
  Thread -> id: 73 -> priority: 1 
,
  Thread -> id: 74 -> priority: 1 
,
  Thread -> id: 75 -> priority: 1 
,
18-20:25:53.326 20_25 -LOG- Started process 'EmpyrionPlayfieldServer.exe' (PID 121) with args: -batchmode -nographics -logFile ../Logs/3283/Playfield_210518-202552-21.log
,
18-20:25:55.575 20_25 -LOG- New playfield server
,
18-20:25:55.577 20_25 -LOG- Thread 'Reader_127.0.0.1:47558' ThreadId=158 ManagedId=12
,
18-20:25:55.577 20_25 -LOG- Thread 'Writer_127.0.0.1:47558' ThreadId=159 ManagedId=13
,
18-20:26:04.133 20_26 -LOG- Booting PfServer (PID 121) starts preparation after 12.1 seconds...
,
18-20:26:06.344 20_26 -LOG- New reserve PfServer (PID 121) ready after 14.3 seconds - count is now: 1
,
18-20:26:21.788 20_26 -ERR- GameServer log on did time out
,
18-20:26:45.994 20_26 -LOG- INFO: Uptime=00h00m 60.313 2058 heap= 251MB fps=39.6 players= 0 pfs=r0/i1/a0 ticks=51276 nwqueue=
,
18-20:27:45.949 20_27 -LOG- INFO: Uptime=00h01m 59.955 2362 heap= 251MB fps=39.7 players= 0 pfs=r0/i1/a0 ticks=52476 nwqueue=
,
18-20:28:45.959 20_28 -LOG- INFO: Uptime=00h02m 60.009 2368 heap= 251MB fps=39.9 players= 0 pfs=r0/i1/a0 ticks=53676 nwqueue=
,
18-20:29:45.980 20_29 -LOG- INFO: Uptime=00h03m 60.021 2368 heap= 251MB fps=39.7 players= 0 pfs=r0/i1/a0 ticks=54877 nwqueue=
,
18-20:30:45.996 20_30 -LOG- INFO: Uptime=00h04m 60.016 2365 heap= 251MB fps=39.7 players= 0 pfs=r0/i1/a0 ticks=56077 nwqueue=
,
18-20:31:46.007 20_31 -LOG- INFO: Uptime=00h05m 60.010 2361 heap= 251MB fps=39.7 players= 0 pfs=r0/i1/a0 ticks=57277 nwqueue=
,
18-20:32:46.014 20_32 -LOG- INFO: Uptime=00h06m 60.007 2370 heap= 251MB fps=40.0 players= 0 pfs=r0/i1/a0 ticks=58477 nwqueue=
,
18-20:33:46.027 20_33 -LOG- INFO: Uptime=00h07m 60.013 2363 heap= 251MB fps=39.7 players= 0 pfs=r0/i1/a0 ticks=59678 nwqueue=
,
18-20:34:46.030 20_34 -LOG- INFO: Uptime=00h08m 60.003 2363 heap= 251MB fps=39.7 players= 0 pfs=r0/i1/a0 ticks=60878 nwqueue=
,
18-20:35:46.034 20_35 -LOG- INFO: Uptime=00h09m 60.003 2370 heap= 251MB fps=39.9 players= 0 pfs=r0/i1/a0 ticks=62078 nwqueue=
,
18-20:36:46.036 20_36 -LOG- INFO: Uptime=00h10m 60.002 2366 heap= 251MB fps=39.7 players= 0 pfs=r0/i1/a0 ticks=63278 nwqueue=
,
18-20:37:46.043 20_37 -LOG- INFO: Uptime=00h11m 60.006 2365 heap= 251MB fps=39.9 players= 0 pfs=r0/i1/a0 ticks=64478 nwqueue=
,

I have a feeling "18-20:26:21.788 20_26 -ERR- GameServer log on did time out" maybe causing my issue

**Comment by BitR** [comment]
Looks like it runs at least.
I've only tried connecting via IP and with Srv_Public: false, so I don't know what's required to get it to show up on the server list. Can you connect to it directly via its IP?

**Comment by daigonstar** [comment]
Yeah which is the weird thing, i've tried direct connecting but just wont have any of it. Ill set srv_Public false see if i get any different results

**Comment by daigonstar** [comment]
Tried last night after a redeployment and still no joy

**Comment by BitR** [comment]
Have you tried disabling the firewall? Did you mess with the iptables flags of dockerd per chance?

**Comment by daigonstar** [comment]
Yeah ive tried disabling ufw still not going up and I havent all i have done is convert the run command to a compose

**Comment by BitR** [comment]
Ah just noticed your port forwards... You need to forward UDP (TCP is default if you don't specify protocol).
So you need these ports in your compose file:
- "30000:30000/udp"
- "30001:30001/udp"
- "30002:30002/udp"
- "30003:30003/udp"

**Comment by daigonstar** [comment]
Just tried that and yep works now able to connect instantly, thanks I really appreciate that! sorry for being a pain
