### ISSUE TITLE
ERROR! Failed to install app '530870' (Disk write failure)

### ISSUE THREAD

**Issue by easehack** [BitR/empyrion-docker#2]
When container is start it result this error : "ERROR! Failed to install app '530870' (Disk write failure)"
I assume it's probably the steam update. Can you help us with this ?

**Comment by BitR** [comment]
Sounds like your permissions are wrong on your volume mounted gamedir.
You'll need to set the owner:group to 1000:1000 (usually the first user on your system).
So if you followed the README, do this: `chown 1000:1000 gamedir`

By default, docker will create directories owned by root:root when doing volume mounts when the directory didn't already exist.

**Comment by easehack** [comment]
Thank you for the quick answer. I did not see I have do change the permissions.
Looks better. Thank you for this project !

**Comment by BitR** [comment]
Yeah, I assumed that you'd create the gamedir and that your userid would be 1000, I might update the README with that info :)

**Comment by MorpheusZero** [comment]
I also continually get this error and I can't figure out what permission is wrong. Am I supposed to be running the `chown` command outside of the entrypoint file and in my host system? (Windows using WSL)??

**Comment by BitR** [comment]
You'll need to run `chown 1000:1000 gamedir` from outside the container.
I haven't tested the image on WSL though, as their actual server is written for Windows.

**Comment by BitR** [comment]
Fixed by commit https://github.com/BitR/empyrion-docker/commit/710fa699479adbd345edc88c04336ef5c60526fd
