### ISSUE TITLE
Can't connect anymore since the last update

### ISSUE THREAD

**Issue by horse-pants** [BitR/empyrion-docker#23]
Hi,
I've been happily using this for years and it's been great, however since the last update, while my server shows in the server list it always times out when I try to connect, nothing else has changed (i.e. ports are still open, all the usual stuff)

Does anyone have any ideas?

(looks like others are having similar issues - https://steamcommunity.com/app/383120/discussions/0/4849904176633370016/)

Cheers

**Comment by BitR** [comment]
Try the latest version of the image, just tested it with RE2 Beta

**Comment by horse-pants** [comment]
Awesome, that seems to have worked

Many thanks
