### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by Andargor** [BitR/empyrion-docker#4]
Hey, this is more of a question and I suspect out of your control. I see very high CPU usage compared to other dedicated servers, even those running on wine. Normally I see 16-25% CPU for other games, but for Empyrion it hovers around the 84% mark even when no one is on.

Any ideas what may be causing this? Is there something that can be done to the container, or is this just bad coding on the Empyrion end?

**Comment by BitR** [comment]
I've updated the image with wine-staging:5.7 as it's the first version I've gotten to work after 4.10.
It's about a 10% change for me in regards to cpu usage, so not much. I tried out a bunch of different proton version, GE version too. These do way better in idle performance, but the server throws an exception when players join (Steamworks GameServer is not initialized.), so it's no good I'm afraid.

Which wine versions have you seen the game run with, where the performance was better?
