### ISSUE TITLE
Server is not working since a recent update to 1.1.x 

### ISSUE THREAD

**Issue by tywilkerson** [BitR/empyrion-docker#5]
The docker server is not working since a recent update to Empyrion, specifically version 1.1.x on August 24th.

**Comment by tywilkerson** [comment]
Not sure how or why but it magically started working.  Thank you.

**Comment by BitR** [comment]
First boot will take a while and steamcmd doesn't really want to flush the current update progress until it's nearly done, so you might've been waiting for an update.
Cool that it works though :)
