### ISSUE TITLE
Invalid platform on steam update/install

### ISSUE THREAD

**Issue by Nibato** [BitR/empyrion-docker#6]
SteamCMD reported the following error when trying to download/install the dedicated server:
`ERROR! Failed to install app '530870' (Invalid platform)`

I was able to fix this issue by modifying entrypoint.sh to run SteamCMD with the following arguments:
```bash
[ "$BETA" ] && ./steamcmd.sh +@sSteamCmdForcePlatformType windows +login anonymous +app_update 530870 -beta experimental +quit
[ -z "$BETA" ] && ./steamcmd.sh +@sSteamCmdForcePlatformType windows +login anonymous +app_update 530870 +quit
```

**Comment by Wannab** [comment]
I also have this issue, but can't find where entrypoint.sh is located so that I can make that modification.

edit: i figured its in the docker container and used docker cp to copy the file out and edit then copy back to the container

**Comment by BitR** [comment]
So are you guys still running the Empyrion server with wine on Windows?

This docker image exists to enable the Empyrion server to run on Linux. You should have no need to run it on this platform that's based on Ubuntu 20.04. I'd recommend setting up a docker image built on Windows instead, so you run the game natively without emulation.

**Comment by Nibato** [comment]
I'm having this issue on fresh installs of Debian 10. 

The issue seems to be that the SteamCMD is detecting that there is no linux version of the dedicated server and refuses to download it when ran on native linux. The command line argument [+@sSteamCmdForcePlatformType windows](https://developer.valvesoftware.com/wiki/SteamCMD#Cross-Platform_Installation) forces app_update to download windows versions of the game.

**Comment by Wannab** [comment]
Same issue with Ubuntu 20.04. The container just exits and continues to restart over and over, when I can attach (if I am quick enough) to container I see the ERROR! Failed to install app '530870' (Invalid platform).

**Comment by BitR** [comment]
Odd, they must've updated steamcmd or it could be down to a newer version of docker.

I've pushed a new version with the changes from @Nibato, docker hub should update with a new build soon.
