### ISSUE TITLE
Suggestion: create docker image for Empyrion-Admin-Helper

### ISSUE THREAD

**Issue by ZeroThinking420** [BitR/empyrion-docker#7]
Hi there, I'm helping some mates host an empyrion dedicated server. We're looking into ways to reduce cost of hosting and one option was to host from ubuntu rather than windows.

I'm using the docker image you've created for Empyrion itself and it seems to work great, however I was wondering if it was possible to create (or help me create) a docker image for Empyrion Admin Helper (EAH) too?

My reasoning behind this is... if I was able to run Empyrion and EAH without GUI on the ubuntu server using docker etc then other admins could remotely connect to EAH with a GUI from their local desktops (windows 10).

Let me know your thoughts, also sorry for posting this as an issue, I can resolve/delete if needed.

**Comment by BitR** [comment]
You'd need to get mono and WPF or wine and dotnet452 (if it actually includes WPF support) working inside the container. I've yet to get a fully automated install going.
I haven't messed about with EAH yet though, so I don't know if it's possible to attach it to a running server over TCP, in which case you won't need to go through the wine hassle.

On a side note, even the NoGui version of EAH requires WPF and can't just be run with mono standalone.

**Comment by ZeroThinking420** [comment]
Right, I will have to look into things and see if I can make any more progress. We did consider running EAH remotely and just connecting to server, but my understanding is you need to run instance of EAH on both servers to use it remotely but there may be other ways like TCP etc, I'm yet to look into it properly too.

Thanks for the tips/advice and getting back to me on this one. I will let you know if I make any progress.

**Comment by AstralDestiny** [comment]
Did anything ever come from this? As in did you get any progress?
