### ISSUE TITLE
Why adding random key?

### ISSUE THREAD

**Issue by firesoft-de** [BitR/empyrion-docker#8]
Hey,

why do you add this key? I don't see any purpose in it.

https://github.com/BitR/empyrion-docker/blob/5860e1cb9fe410c7abef11420403db1056082770/Dockerfile#L7

**Comment by BitR** [comment]
It's the mono key which is required if you want to install mono from their repos.
As you mention, it's not in use.

It's from back when I tried to get the full dedicated server running and not just the EmpyrionDedicated.exe binary.

**Comment by firesoft-de** [comment]
Thanks for the fast answer. So we could remove this line?

**Comment by BitR** [comment]
See commit 8b1df86
