### ISSUE TITLE
centOS8 not working

### ISSUE THREAD

**Issue by Grumbledore667** [BitR/empyrion-docker#9]
Hi there,
I am trying to get the server going on centOS8. sadly it doesnt seem to work. docker hello world works fine. i followed the official docker guide to set docker up and used the steam guide as reference. i am propably just missing something but couldnt figure it out the last couple of days. cheers :D

awesome work on setting this up :D

![image](https://user-images.githubusercontent.com/21963315/100632697-70909300-332d-11eb-942d-451412c1b3e8.png)

**Comment by BitR** [comment]
So it seems there's an issue with thread permissions when it comes to the image and SELinux.

You can run the image with the --privileged flag or by setting the appropriate --cap-add option. I don't know which cap-add capability is needed. You can try out the different capabilities listed in man capabilities until you find the right one, or just the image with --privileged. The issue with --privileged is that it allows for way more privileges than the empyrion server needs, and if someone finds a way to compromise the empyrion server, they might have a way out of docker.
This link might help you out: https://stackoverflow.com/questions/55201028/docker-insufficient-permissions-to-set-thread-priority - they suggest adding --cap_add=sys_nice, to allow thread niceness to be set, although I don't know if that's what steamcmd is complaining about.
Based on the post, here's a handy one-liner to show you docker caps enforced in your container: 
`docker run --rm -i ubuntu:20.04 sh -c 'apt-get update && apt-get install -y libcap2-bin && capsh --print'`

There does seem to be an issue with steamcmd in docker though: https://github.com/steamcmd/docker/issues/30
Just tested it out with `docker run --rm -it bitr/empyrion-server` locally on a ubuntu 20.04 server and it still works just fine, so it must be host related.

**Comment by Grumbledore667** [comment]
--privileged nailed it. in the mean time i allready fixed the docker host bug in centos8. suspected that was the culprint but nope. thx alot. 

https://serverfault.com/questions/987686/no-network-connectivity-to-from-docker-ce-container-on-centos-8

i will look into cap_add once i got everything up and running. my buddy has a server at nitrado which expires so we want to move the stuff over. running a bit short on time now haha.

**Comment by Grumbledore667** [comment]
next issue wine doesnt seem to be working properly.

https://media.discordapp.net/attachments/783461976734957608/783792960776831026/unknown.png

**Comment by BitR** [comment]
It looks like you're not running the entrypoint.sh that sets up the environment for the server to actually run.
If you want to start the server by hand, you'll need to do the same steps as /entrypoint.sh, such as setting up an X11 display, prepare a folder for logs and you'll need to supply -logFile to EmpyrionDedicated.exe or it'll crash on startup.

**Comment by Grumbledore667** [comment]
i used docker start containername to start it since it exits when i launch it with 

docker run --privileged -it -p 30000-30003:30000-30003/udp -v $PWD/gamedir:/home/user/Steam bitr/empyrion-server

i am clueless now. i have near to no experience with docker and linux is quite rusty. was enough to get the ark servers running on my dedi though haha.

**Comment by BitR** [comment]
Alright, what does docker logs say and did you get any logs at $PWD/gamedir/steamapps/common/Empyrion - Dedicated Server/Logs/*/?

**Comment by Grumbledore667** [comment]
[current.log](https://github.com/BitR/empyrion-docker/files/5638438/current.log)
[output.log](https://github.com/BitR/empyrion-docker/files/5638439/output.log)
[wine.log](https://github.com/BitR/empyrion-docker/files/5638440/wine.log)

as for the docker log:

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '530870' already up to date.
+ set -e
+ mkdir -p '/home/user/Steam/steamapps/common/Empyrion - Dedicated Server/DedicatedServer/Logs'
+ rm -f /tmp/.X1-lock
+ export WINEDLLOVERRIDES=mscoree,mshtml=
+ WINEDLLOVERRIDES=mscoree,mshtml=
+ export DISPLAY=:1
+ DISPLAY=:1
+ Xvfb :1 -screen 0 800x600x24
+ cd '/home/user/Steam/steamapps/common/Empyrion - Dedicated Server/DedicatedServer'
+ '[' '' = bash ']'
+ /opt/wine-staging/bin/wine ./EmpyrionDedicated.exe -batchmode -logFile Logs/current.log
+ sh -c 'until [ "`netstat -ntl | tail -n+3`" ]; do sleep 1; done
sleep 5 # gotta wait for it to open a logfile
tail -F Logs/current.log ../Logs/*/*.log 2>/dev/null'

i just copied the last part. it just does nothing after the tail.

what i did:

i created a user called empyrion. created ~/gamedir/

strangely under ~/empyrion/ a new folder named Steam popped up. i think that is related to the issues i am having right now. it contains the empyrion data. 

i had to reinstall everything after one container filled up my whole diskspace with a log file.

**Comment by Grumbledore667** [comment]
deleted all the containers and tried it again with the run. following result:

[empyrion@static ~]$ docker run --privileged -di -p 30000:30000/udp --restart unless-stopped -v $PWD/gamedir:/home/user/Steam bitr/empyrion-server
6fa102fa26b19bcf62298855fdb3ae9fff6df554ecfa4130ecad80faf37338f9
[empyrion@static ~]$ docker ps -a
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                      NAMES
6fa102fa26b1        bitr/empyrion-server   "/entrypoint.sh"    11 seconds ago      Up 10 seconds       0.0.0.0:30000->30000/udp   tender_banach
[empyrion@static ~]$ docker logs tender_banach
+ '[' 0 = 0 ']'
+ mkdir -p /home/user/Steam
+ chown user: /home/user/Steam
+ runuser -u user /entrypoint.sh
+ '[' 1000 = 0 ']'
+ :
+ GAMEDIR='/home/user/Steam/steamapps/common/Empyrion - Dedicated Server/DedicatedServer'
+ cd /home/user
+ set +e
+ '[' '' ']'
+ '[' -z '' ']'
+ ./steamcmd.sh +@sSteamCmdForcePlatformType windows +login anonymous +app_update 530870 +quit
Redirecting stderr to '/home/user/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 51570 KB)...
[  0%] Downloading update (3024 of 51570 KB)...
[  5%] Downloading update (6029 of 51570 KB)...
[ 11%] Downloading update (8523 of 51570 KB)...
[ 16%] Downloading update (11247 of 51570 KB)...
[ 21%] Downloading update (13704 of 51570 KB)...
[ 26%] Downloading update (16410 of 51570 KB)...
[ 31%] Downloading update (18740 of 51570 KB)...
[ 36%] Downloading update (21270 of 51570 KB)...
[ 41%] Downloading update (23985 of 51570 KB)...
[ 46%] Downloading update (26485 of 51570 KB)...
[ 51%] Downloading update (28923 of 51570 KB)...
[ 56%] Downloading update (31477 of 51570 KB)...
[ 61%] Downloading update (32698 of 51570 KB)...
[ 63%] Downloading update (33968 of 51570 KB)...
[ 65%] Downloading update (35207 of 51570 KB)...
[ 68%] Downloading update (36429 of 51570 KB)...
[ 70%] Downloading update (37777 of 51570 KB)...
[ 73%] Downloading update (39024 of 51570 KB)...
[ 75%] Downloading update (40373 of 51570 KB)...
[ 78%] Downloading update (41615 of 51570 KB)...
[ 80%] Downloading update (42865 of 51570 KB)...
[ 83%] Downloading update (44183 of 51570 KB)...
[ 85%] Downloading update (45287 of 51570 KB)...
[ 87%] Downloading update (46533 of 51570 KB)...
[ 90%] Downloading update (47893 of 51570 KB)...
[ 92%] Downloading update (49143 of 51570 KB)...
[ 95%] Downloading update (50506 of 51570 KB)...
[ 97%] Downloading update (51570 of 51570 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/user/Steam/logs/stderr.txt'
/tmp/dumps insufficient permissions - delete and recreate
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@sSteamCmdForcePlatformType" = "windows"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '530870' already up to date.
+ set -e
+ mkdir -p '/home/user/Steam/steamapps/common/Empyrion - Dedicated Server/DedicatedServer/Logs'
+ rm -f /tmp/.X1-lock
+ export WINEDLLOVERRIDES=mscoree,mshtml=
+ WINEDLLOVERRIDES=mscoree,mshtml=
+ export DISPLAY=:1
+ DISPLAY=:1
+ cd '/home/user/Steam/steamapps/common/Empyrion - Dedicated Server/DedicatedServer'
+ '[' '' = bash ']'
+ Xvfb :1 -screen 0 800x600x24
+ /opt/wine-staging/bin/wine ./EmpyrionDedicated.exe -batchmode -logFile Logs/current.log
+ sh -c 'until [ "`netstat -ntl | tail -n+3`" ]; do sleep 1; done
sleep 5 # gotta wait for it to open a logfile
tail -F Logs/current.log ../Logs/*/*.log 2>/dev/null'

**Comment by Grumbledore667** [comment]
So I got it working again. After some digging I figured out that the issue is related to file permission. The server couldnt access the config files that's why it didnt start properly.

Strangely enough the owner of the folders and files in not empyrion but my Main User Account although All are inside the home folder of empyrion. 

Sorry for the trouble.
